# Generated by Django 3.2.4 on 2021-06-21 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=300)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10000)),
                ('todolist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.wishlist')),
            ],
        ),
    ]
